### ISSUE TITLE
Step 3: Executing the Script

### ISSUE THREAD

**Issue by monavariyas** [kshitizShri929/Bash-Scripting-Programming#4]
Please change  :  Now that your script is executable, (.)

**Comment by kshitizShri929** [comment]
it is done

**Comment by monavariyas** [comment]
@kshitizShri929 

It is not done. If you have any confusion you should ask.


To clear your confusion I am attaching screenshot.
![Imagenew](https://github.com/kshitizShri929/Bash-Scripting-Programming/assets/146812602/58b5e798-25e8-4ba8-b4db-20fd0e2ab172)
